# Generated by Django 2.0.6 on 2020-02-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200220_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracker',
            name='task_type',
            field=models.IntegerField(choices=[(1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3'), (3, 'Type 4')]),
        ),
    ]
